# MAPseq Data Analysis

In this notebook, we will take the combined bulk RNAseq from all MAPseq target areas. 

## Imports

In [2]:
import logging
import os
import sys
import traceback

from configparser import ConfigParser

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

gitpath=os.path.expanduser("~/git/mapseq-processing")
sys.path.append(gitpath)
gitpath=os.path.expanduser("~/git/mapseq-analysis")
sys.path.append(gitpath)

from mapseq.core import *
from mapseq.utils import *
from msanalysis.analysis import *

logging.getLogger().setLevel(logging.DEBUG)

print("Done")

Done

## Configuration, logging, and paths for analysis
We need to provide paths to the two fastq read files (either fastq or fastq.gz), the barcode (SSI) sequences for different target areas, and a standard sample info Excel spreadsheet.

In [7]:
cp = get_default_config()
logging.getLogger().setLevel(logging.INFO)
sampleinfo = os.path.expanduser('~/project/mapseq/M211/M211_sampleinfo.xlsx')
outdir = os.path.expanduser('~/project/mapseq/M211/')

mergedfile = os.path.expanduser('~/project/mapseq/M211/ssifasta.out/M211.all.merged.tsv')
rbcm348file = os.path.expanduser('~/project/mapseq/M211/merged.out/ST348.rbcm.tsv')                         
rbcm372file =  os.path.expanduser('~/project/mapseq/M211/merged.out/ST372.rbcm.tsv') 
                               
print("Done")

Done

In [11]:
sampdf = load_sample_info(cp, sampleinfo)
sampdf

/Users/hover/miniconda3/envs/mapseq/lib/python3.9/site-packages/pandas/core/series.py:1021: RuntimeWarning: invalid value encountered in cast
  arr = np.asarray(values, dtype=dtype)
/Users/hover/git/mapseq-processing/mapseq/core.py:59: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace(0,'0',inplace=True)
/Users/hover/git/mapseq-processing/mapseq/core.py:60: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace(np.nan,'', inplace=True)

   usertube ourtube samplename           siteinfo rtprimer  brain region
0         0       1         OB    target-negative      177  ST348     OB
1         0       2       OMCi          injection      185  ST348   OMCi
2         0       3       OMCc             target      178  ST348   OMCc
3         0       4        PAG             target      179  ST348    PAG
4         0       5         OB    target-negative      180  ST372     OB
5         0       6       OMCi          injection      186  ST372   OMCi
6         0       7       OMCc             target      181  ST372   OMCc
7         0       8        PAG             target      182  ST372    PAG
8         0       0    L1 targ        target-lone      183
9         0       0    H2O tag     target-control      184
10        0       0    H2O inj  injection-control      187

In [13]:
alldf = load_df(mergedfile)
alldf

/Users/hover/git/mapseq-processing/mapseq/utils.py:535: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

,sequence,read_count,umi_count,label,type,site,brain,region
0,GTCTCGGTATAATGTCCATCGGTACGTCAGAA,1,1,BC187,lone,injection-control,,187
1,GTGGGGTTGGCGCGTGCGACAAGTCCAAAAAG,1,1,BC187,lone,injection-control,,187
2,TTTGAAAGATTGCTACGGTGGGGCCGGATAGG,1,1,BC187,lone,injection-control,,187
3,TAGGTTGGATTTAAGTCGGGGGCAAGTTAGAA,1,1,BC187,lone,injection-control,,187
4,CATACGCCTTGGGATCGACGGGAAGACTTAAG,1,1,BC187,lone,injection-control,,187
...,...,...,...,...,...,...,...,...
748847,CGTACCAGCCTATGGTTTTGTGCACGTCAGTC,90,1,BC177,spike,target-negative,ST348,177
748848,CGTCGCTAGGTTCAAACACGTTACCGTCAGTC,33,1,BC177,spike,target-negative,ST348,177
748849,CGGTCACTATACACGCATGCACAGCGTCAGTC,1,1,BC177,spike,target-negative,ST348,177
748850,CTAATGCGATTACGCATAGTCTCGCGTCAGTC,11,1,BC177,spike,target-negative,ST348,177
748851,CGTTAGCGGTTGGACGGATGGTTTCGTCAGTC,25,1,BC177,spike,target-negative,ST348,177